# Generated by Django 3.1.12 on 2025-01-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250118_0007'),
        ('users', '0003_auto_20250118_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewed_posts',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
    ]
